services:
  - type: web
    name: admitcard-generator
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx512m -Xms256m"
      - key: FILE_STORAGE_LOCATION
        value: /app/generated
