spring.application.name=admitcard-generator
server.port=${PORT:8080}

# File Storage Configuration
file.storage.location=${FILE_STORAGE_LOCATION:./generated}


# Logging Configuration - Suppress Warnings
logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.com.admitcard=INFO
logging.level.com.itextpdf=ERROR
